trunk_version = "0.21.7"

[build]
target = "index.html"
dist = "dist"
public_url = "https://adrianhill.de/yew-tailwind-test/"

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["update-browserslist-db@latest"]

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "npx @tailwindcss/cli -i tailwind.css -o $TRUNK_STAGING_DIR/tailwind.css --minify"]
