name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Launch Nix devShell
        uses: nicknovitski/nix-develop@v1
      - name: Build page
        run: nix develop --command trunk build
      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: gh-pages
            folder: dist
            single-commit: true
